FROM maven:3.9-eclipse-temurin-23 AS builder

WORKDIR /usr/app

COPY pom.xml .
RUN mvn dependency:resolve

COPY . .
RUN mvn clean install

FROM eclipse-temurin:23-jre-alpine

WORKDIR /usr/app

COPY --from=builder /usr/app/target/hello.world-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
